# define the artifacts folder
# these configrations can be used across the files in the project.
artifacts_root : artifacts # this will create the artifacts folder

# create data ingestion related configuration like path, url. so that we can read it from here.
data_ingestion:
  root_dir: artifacts/data_ingestion # carete data_ingestion folder inside artifacts folder
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# This will create a data_validation folder inside artifacts and verify if train, test and validation folders and  files in it.
data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

#this will create a data_transformation folder to save your transformed data after applying the transformation
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

